# Generated by Django 5.1.7 on 2025-07-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_homepagedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=250)),
                ('event_image', models.ImageField(upload_to='event_images')),
                ('committee', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
            ],
        ),
    ]
