# Generated by Django 5.1.7 on 2025-07-01 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='event_media/images/')),
                ('video', models.FileField(blank=True, upload_to='event_media/videos/')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.events')),
            ],
        ),
    ]
