# Generated by Django 5.1.7 on 2025-07-11 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_eventbooking_eventschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaMelody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('slider_img1', models.ImageField(blank=True, upload_to='cinemaMelody/slider/')),
                ('slider_img2', models.ImageField(blank=True, upload_to='cinemaMelody/slider/')),
                ('slider_img3', models.ImageField(blank=True, upload_to='cinemaMelody/slider/')),
                ('slider_img4', models.ImageField(blank=True, upload_to='cinemaMelody/slider/')),
                ('slider_img5', models.ImageField(blank=True, upload_to='cinemaMelody/slider/')),
                ('slider_title1', models.CharField(max_length=250)),
                ('slider_title2', models.CharField(max_length=300)),
                ('vedio_description1', models.TextField()),
                ('vedio_description2', models.TextField()),
                ('vedio_description3', models.TextField()),
                ('vedio_description4', models.TextField()),
                ('vedio_description5', models.TextField()),
                ('semi_description', models.TextField()),
                ('main_video', models.FileField(blank=True, upload_to='cinemaMelody/mainvideo/')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaMelodyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_malody_image', models.ImageField(blank=True, upload_to='cinemaMelody/images/')),
                ('cinema_melody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melody_images', to='api.cinemamelody')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaMelodyVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_malody_video', models.FileField(blank=True, upload_to='cinemaMelody/videos/')),
                ('cinema_melody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melody_videos', to='api.cinemamelody')),
            ],
        ),
    ]
